version: '3.8'

services: 
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/srv/help
      - ./data:/srv/data
      - ./data/.parisneo:/root/.parisneo/
      - ./configs:/srv/configs
      - ./web:/srv/web
    ports: 
      - "9600:9600"
